config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'
  resources :tasks 
  
  resources :checklists 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
    belongs_to :task
    has_many :likes
   
    scope :recent, -> { order(created_at: :desc) }
    
    def task
        return Task.find_by(id: self.task_id)
    end
    
    private
    
    def validate_name_not_including_comma
        errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
    end
    
    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end
    
    def self.search(search)
        if search
            Checklist.where(['try LIKE ?',"%#{search}%"])
        else
            Checklist.all
        end
    end
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    has_many :checklists, dependent: :destroy
    validates :name, presence: true
    validates :name, length: { maximum: 30 }
    validate :validate_name_not_including_comma
    
    scope :recent, -> { order(created_at: :desc) }
    
    private
    
    def validate_name_not_including_comma
        errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
    end
    
    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    
    has_many :tasks
    has_many :likes
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all.order(created_at: :desc)
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
  
  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 helper_method :current_user
 helper_method :current_task
 before_action :login_required
 
 private
 
 def current_user
     @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
 end
 
 def login_required
  redirect_to login_path unless current_user
 end
 
 def current_task
  @current_task = Task.find_by(id: session[:task_id]) 
 end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :set_checklist, only: [:show, :edit, :update, :destroy]
  
  def index
    @checklists = current_task.checklists.order(created_at: :desc).paginate(page: params[:page],per_page:10).search(params[:search])
  end
  
  def new
    @checklist = Checklist.new
  end

  def show
  end

  def create
     @checklist = Checklist.new(checklist_params)
     @checklist.task_id = current_task.id
     @checklist.save
     redirect_to checklists_url, notice: "チェックリスト「#{@checklist.date}」を登録しました"
  end
  
  def update
    @checklist.update!(checklist_params)
    @checklist.save
    redirect_to checklists_url, notice: "「#{@checklist.date}」を更新しました。"
  end

  def edit
  end

  def destroy
    @checklist.destroy
    redirect_to checklists_url, notice: "「#{@checklist.date}」を削除しました。"
  end
  
  private
  
  def checklist_params
    params.require(:checklist).permit(:date, :try, :review, :reason, :comment)
  end
  
  def set_checklist
    @checklist = Checklist.find_by(id: params[:id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
  end
  
  def create
    user = User.find_by(email: session_params[:email])
    
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      render :new
    end
  end
  
  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end
  
  private
  
    def session_params
      params.require(:session).permit(:email, :password)
    end
      
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
    @tasks = current_user.tasks.order(created_at: :desc)
  end

  def show
    @task = Task.find_by(id: params[:id])
    @checklists = @task.checklists.search(params[:search])
    @checklists = @checklists.paginate(page: params[:page],per_page:10)
    session[:task_id] = @task.id
    @task.save!
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(task_params.merge(user_id: current_user.id))
    if @task.save
      redirect_to @task, notice: "習慣「#{@task.name}」を登録しました"
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    @task.update!(task_params)
    redirect_to tasks_url, notice: "「#{@task.name}」を更新しました。"
  end
  
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "「#{@task.name}」を削除しました。"
  end
  
  private
  
  def task_params
    params.require(:task).permit(:name, :purpose)
  end
  
  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
   - user.errors.full_messages.each do |message|
     li = message

= form_with model: [:admin, @user], local: true do |f|
  .form-group
   = f.label :name, '名前'
   = f.text_field :name, class: 'form-control'
  .form-group
   = f.label :email, 'メールアドレス'
   = f.text_field :email, class: 'form-control'
  .form-check
   = f.label :admin, class: 'form-check-label' do
    = f.check_box :admin, class: 'form-check-input'
    | 管理者権限
  .form-group
   = f.label :password, 'パスワード'
   = f.password_field :password, class: 'form-control'
  .form-group
   = f.label :password_confirmation, 'パスワード(確認)'
   = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
    = link_to '一覧', admin_users_path, class: 'nav-link'
    
= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-parimary'

.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th = User.human_attribute_name(:name)
            th = User.human_attribute_name(:email)
            th = User.human_attribute_name(:admin)
            th = User.human_attribute_name(:created_at)
            th = User.human_attribute_name(:updated_at)
            th
    tbody
        - @users.each do |user|
            tr
                td = link_to user.name, [:admin, user]
                td = user.email
                td = user.admin?
                td = user.created_at
                td = user.updated_at
                td
                   = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
                   = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
    = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
    = link_to '一覧', admin_users_path, class: 'nav-link'
    
table.table.table-hover
    tbody
        tr
            th = User.human_attribute_name(:id)
            td = @user.id
        tr
            th = User.human_attribute_name(:name)
            td = @user.name
        tr
            th = User.human_attribute_name(:email)
            td = @user.email
        tr
            th = User.human_attribute_name(:admin)
            td = @user.admin? ? 'あり' : 'なし'
        tr
            th = User.human_attribute_name(:created_at)
            td = @user.created_at
        tr
            th = User.human_attribute_name(:updated_at)
            td = @user.updated_at
            
= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/checklists/_form.html.slim
= form_with model: checklist, local: true do |f|
  .form-group
    = f.label :date
    = f.text_field :date, class: 'form-control', id: 'checklist_date'
  .form-group
    = f.label :try
    = f.text_field :try, class: 'form-control', id: 'checklist_try'
  .form-group
  #star
    = f.label :review
    = f.hidden_field :review, id: 'review_star'
    javascript:
     $('#star').raty({
      size: 36,
      starOff: "#{asset_path('star-off.png')}",
      starOn: "#{asset_path('star-on.png')}",
      starHalf: "#{asset_path('star-half.png')}",
      scoreName: 'checklist[review]',
      half: true,
     });
  .form-group
    = f.label :comment
    = f.text_area :comment, class: 'form-control', id: 'checklist_comment'
  = f.submit nil, class: 'btn btn-primary'
  
 

app/views/checklists/edit.html.slim
h1 チェックリストの編集

.nav.justify-content-end
  = link_to '一覧', task_path, class: 'nav-link'
    
= render partial: 'form', locals: { checklist: @checklist }

app/views/checklists/index.html.slim
h1 チェックリスト一覧

h3 毎日の行動を記録して、工夫して改善していこう！


= link_to '記録する', new_checklist_path, class: 'btn btn-primary'
.search-form
= form_tag(checklists_path, method: :get) do
    = text_field_tag :search
    = submit_tag '検索', :name => nil

.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th = Checklist.human_attribute_name(:date)
            th = Checklist.human_attribute_name(:try)
            th = Checklist.human_attribute_name(:review)
            th
    tbody
        = will_paginate @checklists, :previous_label => ' &lt 前へ', :next_label => '次へ &gt'
        - @checklists.each do |checklist|
            tr
                td = checklist.date
                td = checklist.try
                #star-rate-checklist.id
                td = checklist.review
                td 
                 = link_to '編集', edit_checklist_path(checklist), class: 'btn btn-primary mr-3'
                 = link_to '削除', checklist, method: :delete, data: { confirm: "「#{checklist.date}」を削除しました。" }, class: 'btn btn-danger'
                
                 javascript: 
                    $('#star-rate-checklist.id').raty({
                    size: 36,
                    starOff: "#{asset_path('star-off.png')}",
                    starOn: "#{asset_path('star-on.png')}",
                    starHalf: "#{asset_path('star-half.png')}",
                    half: true,
                    readOnly: true,
                    score: checklist.review,
                    });
.
table.table-sm.table-hover
    thead.thead-default
        tr
            th = Checklist.human_attribute_name(:past_try)
    tbody
        - @checklists.pluck(:try).uniq.each do |checklist|
            tr
                td = checklist

app/views/checklists/new.html.slim
h1 チェックリストの新規登録

.nav.justify-content-end
  = link_to '一覧', checklists_path, class: 'nav-link'
    
= render partial: 'form', locals: { checklist: @checklist }

app/views/checklists/show.html.slim
.nav.justify-content-end
 = link_to 'チェックリスト一覧', checklists_path, class: 'nav-link'
table.table.table-hover
    tbody
        tr
            th = Checklist.human_attribute_name(:try)
            td = @checklist.try
            
= link_to '編集', edit_checklist_path, class: 'btn btn-primary mr-3'
= link_to '削除', @checklist, method: :delete, data: { confirm: "タスク「#{@checklist.try}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | HabitsSheet
    = csrf_meta_tags
    = csrf_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
    body
      .app-title.navbar.navbar-expand-md.navbar-light.bg-light
        .navbar-brand HabitsSheet
        
        ul.navbar-nav.ml-auto
          - if current_user
            li.nav-item = link_to '習慣一覧', tasks_path, class: 'nav-link'
            - if current_user.admin?
            li.nav-item = link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
            li.nav-item = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
          - else
            li.nav-item = link_to 'ログイン', login_path, class: 'nav-link'
      .container
        - if flash.notice.present?
          .alert.alert-success = flash.notice
        = yield

app/views/tasks/_form.html.slim
= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :purpose
    = f.text_field :purpose, class: 'form-control', id: 'task_purpose'
  = f.submit nil, class: 'btn btn-primary'
  

app/views/tasks/edit.html.slim
h1 習慣の編集

.nav.justyfy-content-end
    = link_to '一覧', tasks_path, class: 'nav-link'
    
= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1 習慣一覧

p 身に付けたい習慣を一つだけ決めて、継続していこう！

= link_to '新規登録', new_task_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th = Task.human_attribute_name(:name)
            th = Task.human_attribute_name(:created_at)
            th
    tbody
        - @tasks.each do |task|
            tr
                td = link_to task.name, task
                td = task.created_at
                td 
                 = link_to 'チェックリスト', task_path(task), class: 'btn btn-success mr-3'
                 = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
                 = link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除しました。" }, class: 'btn btn-danger'
                
                 
                 
    

app/views/tasks/new.html.slim
h1 習慣の新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
    
= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.slim
h1 チェックリスト一覧
h3 毎日の行動を記録して、工夫して改善していこう！
<br>
h1 ="『#{@task.name}』"
<br>
= link_to '記録する', new_checklist_path, class: 'btn btn-primary' 
<br>
.search-form
= form_tag(task_path, method: :get) do
    = text_field_tag :search
    = submit_tag '検索', :name => nil

.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th = Checklist.human_attribute_name(:date)
            th = Checklist.human_attribute_name(:try)
            th = Checklist.human_attribute_name(:review)
            th
    tbody
        = will_paginate @checklists, :previous_label => ' &lt 前へ', :next_label => '次へ &gt'
        - @checklists.each do |checklist|
            tr
                td = checklist.date
                td = checklist.try
                #star-rate-checklist.id
                td = checklist.review
                td 
                 = link_to '編集', edit_checklist_path(checklist), class: 'btn btn-primary mr-3'
                 = link_to '削除', checklist, method: :delete, data: { confirm: "本当に「#{checklist.date}」を削除しますか？" }, class: 'btn btn-danger'
                
                 javascript: 
                    $('#star-rate-checklist.id').raty({
                    size: 36,
                    starOff: "#{asset_path('star-off.png')}",
                    starOn: "#{asset_path('star-on.png')}",
                    starHalf: "#{asset_path('star-half.png')}",
                    half: true,
                    readOnly: true,
                    score: checklist.review,
                    });
.
table.table-sm.table-hover
    thead.thead-default
        tr
            th = Checklist.human_attribute_name(:past_try)
    tbody
        - @checklists.pluck(:try).uniq.each do |checklist|
             tr
                td = checklist
             